print("+++++++++++++++++++++++++++++++++++++++++++++++++")
print("+   Sollicitatieformulier \"Ruimte-vuilsnisman\"  + ")
print("+++++++++++++++++++++++++++++++++++++++++++++++++")
print("Er wordt u een aantal relevante vragen gesteld...")
print("Gelieve die naar eer en geweten in te vullen")
print("Als blijkt dat u aan de criteria voldoet dan komt u in")
print("aanmerking voor een serieus sollicitatiegesprek!")
print('LET OP!!! -Antwoord alleen met \'ja\' of \'nee\'-')
print("Ontspan maar blijf wakker, hier komen de vragen")
print("Ready?")
print("Set")
print("Go")
print("Ga je gang")
print("Waar wacht je nog op?")
print("Ben je bang?")
print("+++++++++++++++++++++++++++++++++++++++++++++++++")

jongleerErvaring = int(input('Hoeveel jaar heeft u ervaring met jongleren?: '))
mboOndernemen = input('Doet u een MBO-4 opleiding \'Ondernemen\'? ja /nee: ')
vrachtBewijs = input('Heeft u een Vrachtwagen rijbewijs? ja/nee: ')
hogeHoed = input('Bent u in bezit van een hoge hoed? ja/nee: ')
geslacht = input('Wat is je geslacht? man/vrouw: ')
if geslacht == 'man':
    snorBreedte = int(input('Wat is uw snorbreedte in centimeters?: '))
    lengte = int(input('Hoe lang bent u?: '))
    gewicht = int(input('Hoeveel weegt u?: '))
    raarCertificaat = input('Bent u in bezit van het certificaat \"Overleven met gevaarlijk personeel\"? ja/nee: ')
    mountainBike = input('Heeft u een mountainbike? ja/nee: ')
    vingers = int(input('Hoeveel vingers heeft u?: '))
    diameterLinkerOogbal = int(input('Wat is de diameter van uw linker oogbal in centimeters?: '))
    paardrijEenSport = input('Vind u dat paardrijen een sport is? ja/nee: ')
elif geslacht == 'vrouw':
    krulLengte = int(input('Wat is de lengte van uw krulhaar in centimeters?: '))
    lengte = int(input('Hoe lang bent u?: '))
    gewicht = int(input('Hoeveel weegt u?: '))
    raarCertificaat = input('Bent u in bezit van het certificaat \"Overleven met gevaarlijk personeel\"? ja/nee: ')
    mountainBike = input('Heeft u een mountainbike? ja/nee: ')
    vingers = int(input('Hoeveel vingers heeft u?: '))
    diameterLinkerOogbal = int(input('Wat is de diameter van uw linker oogbal in centimeters?: '))
    paardrijEenSport = input('Vind u dat paardrijen een sport is? ja/nee: ')

if geslacht == 'vrouw' and jongleerErvaring >= 5 and mboOndernemen == 'ja' and vrachtBewijs == 'ja' and hogeHoed == 'ja' and lengte >= 150 and gewicht >= 90 and raarCertificaat == 'ja' and krulLengte >= 20:
    print('Gefeliciteerd! U kunt volgende week op een sollicitatiegesprek komen.')
elif geslacht == 'man' and snorBreedte >= 10 and jongleerErvaring >= 5 and mboOndernemen == 'ja' and vrachtBewijs == 'ja' and hogeHoed == 'ja' and lengte >= 150 and gewicht >= 90 and raarCertificaat == 'ja' and krulLengte >= 20:
    print('Gefeliciteerd! U kunt volgende week op een sollicitatiegesprek komen.')
else:
    print('Helaas, u komt niet in aanmerking voor deze baan')
